---
version: '2'
services:
  registry:
    image: registry:2.5
    ports:
      - "5000:5000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - REGISTRY_STORAGE=s3
      - REGISTRY_STORAGE_S3_ACCESSKEY=${AWS_ACCESS_KEY_ID}
      - REGISTRY_STORAGE_S3_SECRETKEY=${AWS_SECRET_ACCESS_KEY}
      - REGISTRY_STORAGE_S3_REGION
      - REGISTRY_STORAGE_S3_BUCKET
      - REGISTRY_STORAGE_S3_ROOTDIRECTORY=/
