---
- hosts: all
  pre_tasks:
    - set_fact:
        registry_storage_s3_region: "{{ registry_storage_s3_region|default('ap-northeast-1') }}"
        registry_storage_s3_rootdirectory: "{{ registry_storage_s3_rootdirectory|default('/') }}"
        registry_storage_s3_accesskey: "{{ registry_storage_s3_accesskey|default('') }}"
        registry_storage_s3_secretkey: "{{ registry_storage_s3_secretkey|default('') }}"
        registry_docker_command_become: "{{ registry_docker_command_become|default(false) }}"
  tasks:
    - block:
      - name: Check whether registry already runs
        command: docker inspect service-registry
        register: check_registry_run
        changed_when: no
        ignore_errors: yes
      - name: Start registry container
        shell: >+
          docker run -d -p 5000:5000 --name service-registry
          -e REGISTRY_STORAGE=s3
          -e REGISTRY_STORAGE_S3_REGION={{ registry_storage_s3_region }}
          -e REGISTRY_STORAGE_S3_BUCKET={{ registry_storage_s3_bucket }}
          -e REGISTRY_STORAGE_S3_ROOTDIRECTORY={{ registry_storage_s3_rootdirectory }}
          -e REGISTRY_STORAGE_S3_ACCESSKEY={{ registry_storage_s3_accesskey }}
          -e REGISTRY_STORAGE_S3_SECRETKEY={{ registry_storage_s3_secretkey }}
          registry:2.5
        when: check_registry_run.rc != 0
      become: "{{ registry_docker_command_become|bool }}"
