---
- hosts: all
  pre_tasks:
    - set_fact:
        registry_docker_command_become: "{{ registry_docker_command_become|default(false) }}"
  tasks:
    - name: Check whether docker daemon runs
      command: docker ps
      register: check_docker_run
      become: "{{ registry_docker_command_become|bool }}"
    - block:
      - name: Check whether registry already runs
        command: docker inspect service-registry
        register: check_registry_run
        changed_when: no
        ignore_errors: yes
      - name: Stop registry container
        command: docker rm -f service-registry
        when: check_registry_run.rc == 0
      become: "{{ registry_docker_command_become|bool }}"
      when: check_docker_run.rc == 0
